package com.example.application.views.dashboard;

import com.example.application.data.SamplePerson;
import com.example.application.services.SamplePersonService;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import com.vaadin.flow.spring.data.VaadinSpringDataHelpers;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;

@PageTitle("Dashboard")
@Route(value = "dashboard")
@RouteAlias(value = "")
@Uses(Icon.class)
public class DashboardView extends Composite<VerticalLayout> {

    public DashboardView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H1 h1 = new H1();
        HorizontalLayout layoutRow = new HorizontalLayout();
        Button buttonPrimary = new Button();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        Button buttonPrimary2 = new Button();
        H2 h2 = new H2();
        Grid basicGrid = new Grid(SamplePerson.class);
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        Button buttonPrimary3 = new Button();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        Button buttonPrimary4 = new Button();
        FormLayout formLayout2Col = new FormLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H2 h22 = new H2();
        Paragraph textMedium = new Paragraph();
        Paragraph textMedium2 = new Paragraph();
        Paragraph textMedium3 = new Paragraph();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H2 h23 = new H2();
        Paragraph textMedium4 = new Paragraph();
        Paragraph textMedium5 = new Paragraph();
        Paragraph textMedium6 = new Paragraph();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        H2 h24 = new H2();
        Paragraph textMedium7 = new Paragraph();
        Paragraph textMedium8 = new Paragraph();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        getContent().setJustifyContentMode(JustifyContentMode.START);
        getContent().setAlignItems(Alignment.CENTER);
        layoutColumn2.setWidthFull();
        getContent().setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("60%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        h1.setText("Dashboard");
        layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, h1);
        h1.setWidth("max-content");
        layoutRow.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("100px");
        layoutRow.setAlignItems(Alignment.CENTER);
        layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
        buttonPrimary.setText("Mannschaft hinzufügen");
        layoutRow.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary);
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutRow2.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        layoutRow2.setAlignItems(Alignment.CENTER);
        layoutRow2.setJustifyContentMode(JustifyContentMode.END);
        buttonPrimary2.setText("Tabelle löschen");
        layoutRow2.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary2);
        buttonPrimary2.setWidth("min-content");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        h2.setText("Tabelle");
        h2.setWidth("max-content");
        layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, basicGrid);
        basicGrid.setWidth("100%");
        basicGrid.getStyle().set("flex-grow", "0");
        setGridSampleData(basicGrid);
        layoutRow3.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("100px");
        layoutRow3.setAlignItems(Alignment.CENTER);
        layoutRow3.setJustifyContentMode(JustifyContentMode.CENTER);
        buttonPrimary3.setText("Spiele hinzufügen");
        layoutRow3.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary3);
        buttonPrimary3.setWidth("min-content");
        buttonPrimary3.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        layoutRow4.setHeightFull();
        layoutRow3.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        layoutRow4.setAlignItems(Alignment.CENTER);
        layoutRow4.setJustifyContentMode(JustifyContentMode.END);
        buttonPrimary4.setText("Spiele bearbeiten");
        layoutRow4.setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary4);
        buttonPrimary4.setWidth("min-content");
        buttonPrimary4.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        formLayout2Col.setWidth("100%");
        layoutColumn3.setHeightFull();
        formLayout2Col.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        h22.setText("Ergebnisse");
        h22.setWidth("max-content");
        textMedium.setText("Fc Basel - Fc Zürich - 3:2");
        textMedium.setWidth("100%");
        textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
        textMedium2.setText("Fc Luzern - Fc Sion - 1:3");
        textMedium2.setWidth("100%");
        textMedium2.getStyle().set("font-size", "var(--lumo-font-size-m)");
        textMedium3.setText("Fc Thun - BSC Young Boys - 1:1");
        textMedium3.setWidth("100%");
        textMedium3.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutColumn4.setHeightFull();
        formLayout2Col.setFlexGrow(1.0, layoutColumn4);
        layoutColumn4.setWidth("100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        h23.setText("Heading");
        h23.setWidth("max-content");
        textMedium4.setText("Fc Basel - BSC Young Boys");
        textMedium4.setWidth("100%");
        textMedium4.getStyle().set("font-size", "var(--lumo-font-size-m)");
        textMedium5.setText("Fc Sion - Fc Thun");
        textMedium5.setWidth("100%");
        textMedium5.getStyle().set("font-size", "var(--lumo-font-size-m)");
        textMedium6.setText("Fc Zürich - Fc Luzern");
        textMedium6.setWidth("100%");
        textMedium6.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutColumn5.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn5);
        layoutColumn5.setWidth("100%");
        layoutColumn5.getStyle().set("flex-grow", "1");
        h24.setText("News");
        h24.setWidth("max-content");
        textMedium7.setText("Fc Basel: Valentin Stocker trifft 3 mal gegen Zürich und bringt den Hattrick nach Hause!");
        textMedium7.setWidth("100%");
        textMedium7.getStyle().set("font-size", "var(--lumo-font-size-m)");
        textMedium8.setText("Fc Zürich: Zürich schiesst 2 Tore gegen Basel und verliert knapp mit 2:3!");
        textMedium8.setWidth("100%");
        textMedium8.getStyle().set("font-size", "var(--lumo-font-size-m)");
        getContent().add(layoutColumn2);
        layoutColumn2.add(h1);
        layoutColumn2.add(layoutRow);
        layoutRow.add(buttonPrimary);
        layoutRow.add(layoutRow2);
        layoutRow2.add(buttonPrimary2);
        layoutColumn2.add(h2);
        layoutColumn2.add(basicGrid);
        layoutColumn2.add(layoutRow3);
        layoutRow3.add(buttonPrimary3);
        layoutRow3.add(layoutRow4);
        layoutRow4.add(buttonPrimary4);
        layoutColumn2.add(formLayout2Col);
        formLayout2Col.add(layoutColumn3);
        layoutColumn3.add(h22);
        layoutColumn3.add(textMedium);
        layoutColumn3.add(textMedium2);
        layoutColumn3.add(textMedium3);
        formLayout2Col.add(layoutColumn4);
        layoutColumn4.add(h23);
        layoutColumn4.add(textMedium4);
        layoutColumn4.add(textMedium5);
        layoutColumn4.add(textMedium6);
        layoutColumn2.add(layoutColumn5);
        layoutColumn5.add(h24);
        layoutColumn5.add(textMedium7);
        layoutColumn5.add(textMedium8);
    }

    private void setGridSampleData(Grid grid) {
        grid.setItems(query -> samplePersonService.list(
                PageRequest.of(query.getPage(), query.getPageSize(), VaadinSpringDataHelpers.toSpringDataSort(query)))
                .stream());
    }

    @Autowired()
    private SamplePersonService samplePersonService;
}
